# Where the exercises etc go, given the solutions

[solution.metrics]
out_path = '{one_down}/findoutlie/metrics.py'

[solution.validate_data]
out_path = '{one_down}/scripts/validate_data.py'

[solution.detectors]
out_path = '{one_down}/findoutlie/detectors.py'
